Fixes #260 - replaces Travis with GH Action workflow
apex-enterprise-patterns/fflib-apex-common pull request #295
Opened 2020-08-18 21:17 UTC by daveespo

This is my basic cut at a GH Action Workflow 

Fanc(ier) things that we can add some day:
 * Status badge for the README
 * Orchestration via the GH API to trigger builds in other respositories (https://github.com/apex-enterprise-patterns/fflib-apex-common-samplecode is the one that comes to mind)

2020-09-29 17:17 UTC, stohn777 requested changes

2020-09-29 17:17 UTC, stohn777 commented on .github/workflows/deploy.and.test.yml
> +        run: sfdx force:org:delete -p
@daveespo Here's what I've used before ...
```
-   name: Finalize
    if: always()
    run: sfdx force:org:delete -p -u $SCRATCH_ORG_NAME -v $DEV_HUB_NAME
```

2020-09-30 17:40 UTC, stohn777 submitted a review, later dismissed

2021-01-21 13:17 UTC, ImJohnMDaniel approved these changes

2021-01-21 23:10 UTC, stohn777 approved these changes

2021-01-22 01:50 UTC, merged