Starting with minor optimization and reduce #lines of code
apex-enterprise-patterns/fflib-apex-common pull request #328
Opened 2021-04-15 06:17 UTC by rahulchaudharyofficial

Starting with minor changes, please review.

2021-04-15 11:01 UTC, wimvelzeboer requested changes

2021-04-15 11:22 UTC, ImJohnMDaniel commented
@rahulchaudharyofficial can you first discuss more about what your intentions are with this PR please?  Is there an issue that this trying to solve?  Why should this change be needed?  Thanks for the help.

2021-04-16 04:35 UTC, rahulchaudharyofficial commented on sfdx-source/apex-common/main/classes/fflib_SObjectDescribe.cls
> +			if(!String.isBlank(name))
Thank you for the feedback.
my intention is to not compare strings directly with null and let String class's isBlank method deal with it's null or blank possibilities.
I do agree that Negative or Positive are both ways of writing the block but readability in this non complex scenario is not a huge factor.
Existing code was nested with multiple if clauses and i am trying to reduce it.

2021-04-16 04:40 UTC, rahulchaudharyofficial commented
@ImJohnMDaniel My intensions are following

a) I am trying to remove explicit null checks against a string and use String's build in API which checks for null as well as Blank string.
b) I am trying to avoid multiple nesting of block.
c) From functional point of view this PR do not change anything but idea here is to make it more compact and concise.

2021-04-27 15:48 UTC, daveespo commented
We're going to reject this PR -- while we appreciate the need to refactor, we would like that coupled with a functional need for the refactoring (i.e. fixing a bug or adding new functionality)

Just moving around code for readability creates unnecessary risk.

2021-04-27 15:48 UTC, closed without merging